# Generated by Django 3.0.5 on 2020-04-25 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelTunnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_id', models.CharField(max_length=50, verbose_name='ID первого канала')),
                ('from_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя первого канала')),
                ('to_id', models.CharField(max_length=50, verbose_name='ID второго канала')),
                ('to_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя второго канала')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(max_length=20)),
                ('api_hash', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Дата последней активности')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_message_id', models.CharField(max_length=50, verbose_name='ID оригинального сообщения')),
                ('to_message_id', models.CharField(max_length=50, verbose_name='ID копии сообщения')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.ChannelTunnel')),
            ],
        ),
        migrations.AddField(
            model_name='channeltunnel',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.TelegramClient'),
        ),
    ]
